-- MySQL Script generated by MySQL Workbench
-- dom 15 may 2016 17:35:15 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema heineken-form
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema heineken-form
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `heineken-form` DEFAULT CHARACTER SET utf8 ;
USE `heineken-form` ;

-- -----------------------------------------------------
-- Table `heineken-form`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heineken-form`.`usuario` (
  `idusuarios` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `dpi` VARCHAR(45) NOT NULL,
  `idCodigo` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL,
  PRIMARY KEY (`dpi`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `heineken-form`.`codigo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `heineken-form`.`codigo` (
  `idcodigo` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(45) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `update_at` DATETIME NOT NULL,
  PRIMARY KEY (`idcodigo`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
